services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d snetlogs-db"]
      interval: 5s
      timeout: 5s
      retries: 10
    dns:
      - 1.1.1.1
      - 8.8.8.8

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8080"
    dns:
      - 1.1.1.1
      - 8.8.8.8

volumes:
  pgdata:
